### ISSUE TITLE
[BUG] No access to the option "Use Local Lan Server" on server DropDownList

### ISSUE THREAD

**Issue by Patapignouf** [luskaner/ageLANServerLauncherCompanion#1]
Hello,
Thanks for your work on this awesome project.
I try to use your work fully offline. 
I'have started the server successfully and the client found it when started.
But in game i cannot access to the option "Use Local Lan Server" on server dropDownList. I only have the "default" option.

The DLL of this repo has been setup on the "dlls" folder and i have correctly modify the _ColdClientLoader.ini_ with _DllsToInjectFolder=dlls_.

Can you help me ?

![image](https://github.com/user-attachments/assets/3fa0386d-26e1-4ec9-91b8-e5d54616e4a1)

**Comment by luskaner** [comment]
Hello @Patapignouf:

This issue is not related to this project (or my server main project) as your game is unable to detect your own BattleServer.exe on your PC (this is the match server included in the game).

There are a couple of things to try out:
* Disable/De-prioritize superfluous windows adapters (like virtual adapters) making sure your LAN adapter priority is at the top when you run `ipconfig`. Look on the internet on how to do it.
* Disable your windows firewall.
* Check `BattleServer.exe` process is running with the Task Manager when you do this.
* On the launcher config, set `CanBroadcastBattleServer` to `false`.

**Comment by Patapignouf** [comment]
You're right, that was just the firewall blocking the _BattleServer.exe_ process. I can now host a game on LAN without internet awesome. Ty
